version: "2.4"

services:
  ros_noetic:
    container_name: ROS_NoeticFoxy
    image: roboylabs/ros_foxy_noetic_vnc:vnc
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display

    ports:
      - "6083:80"
    volumes:
      - ./data:/home/data

